apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc
  labels:
    name:  nfs-sc
    zone: hanoi-vietnam
provisioner: taquy.com/nfs
parameters:
  archiveOnDelete: "false"
allowVolumeExpansion: true
reclaimPolicy: Retain
