kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
  labels:
    name: nfs-client-provisioner
    zone: hanoi-vietnam
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-client-provisioner
      zone: hanoi-vietnam
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: nfs-client-provisioner
        zone: hanoi-vietnam
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /data
          env:
            - name: PROVISIONER_NAME
              value: taquy.com/nfs
            - name: NFS_SERVER
              value: 172.16.42.138
            - name: NFS_PATH
              value: /data
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.16.42.138
            path: /var/nfs_share_dir 