# Define Persistence Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-pv
  namespace: taquy
  labels:
    zone: hanoi-vietnam
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: taquy
    name: nfs-server-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - taquy
---
# Define Persistence Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pvc
  namespace: taquy
  labels:
    name: nfs-server-pvc
    zone: hanoi-vietnam
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Define Service
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  namespace: taquy
  labels:
    zone: hanoi-vietnam
spec:
  clusterIP: 10.96.0.5
  selector:
    app: nfs-server
    zone: hanoi-vietnam
  ports:
    # Port 2049 for TCP
    - name: nfs-tcp
      port: 2049
      protocol: TCP
    # Port 111 for UDP
    - name: nfs-upd
      port: 111
      protocol: UDP
---
# Define Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: taquy
  labels:
    name: nfs-server
    zone: hanoi-vietnam
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: nfs-server
      zone: hanoi-vietnam
  template:
    metadata:
      name: nfs-server
      namespace: taquy
      labels:
        name: nfs-server
        zone: hanoi-vietnam
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:12
          ports:
            - containerPort: 2049
              name: nfs-tcp
            - containerPort: 111
              name: nfs-upd
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: "/data"
          volumeMounts:
            - name: nfs-storage
              mountPath: /data
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-server-pvc
