version: '3'
services:
  # jenkins-server:
  #   image: 397818416365.dkr.ecr.us-east-1.amazonaws.com
  ms-db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "aD@R98xaYEctkKCn"
      ACCEPT_EULA: "Y"
    ports:
      - 1401:1433
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "aD@R98xaYEctkKCn", "-Q", "select 1"]
      interval: 10s
      retries: 10
    volumes:
      - sqlvolume:/var/opt/mssql
  octopus-server:
    image: octopusdeploy/octopusdeploy:latest
    privileged: true
    user: root
    environment:
      ACCEPT_EULA: "Y"
      OCTOPUS_SERVER_NODE_NAME: taquy
      DB_CONNECTION_STRING: Server=ms-db,1433;Database=OctopusDeploy;User=sa;Password=aD@R98xaYEctkKCn
      ADMIN_USERNAME: root
      ADMIN_PASSWORD: "aD@R98xaYEctkKCn"
      ADMIN_EMAIL: taquy.pb@gmail.com
      # openssl rand 16 | base64
      MASTER_KEY: txEh15FjdRzdNhLroMNb1w==
      DISABLE_DIND: "Y"
    ports:
      - 8080:8080
      - 11111:10943
    depends_on:
      - ms-db
    volumes:
      - repository:/repository
      - artifacts:/artifacts
      - taskLogs:/taskLogs
      - cache:/cache
      - import:/import
volumes:
  repository:
  artifacts:
  taskLogs:
  cache:
  import:
  sqlvolume: