apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo
  namespace: taquy
  labels:
    zone: hanoi-vietnam
spec:
  storageClassName: mongo
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    fsType: ext4
    path: /mnt/taquy/mongo  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - taquy