apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: taquy
  labels:
    zone: hanoi-vietnam
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi