apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: taquy
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: taquy-api
      zone: hanoi-vietnam
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      namespace: taquy
      labels:
        app: taquy-api
        zone: hanoi-vietnam
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_DATABASE
            value: taquy
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: root1234
        volumeMounts:
          - name: mongo
            mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=test"
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo