apiVersion: v1
kind: Service
metadata:
  name: taquy.api-svc
spec:
  selector:
    app: taquy-api
    zone: hanoi-vietnam
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
