version: '3'

networks:
  taquy-proxy:
    external: true
    name: taquy-proxy

volumes:
  traefik-ssl-vol:
    external: true

services:
  # https://github.com/authelia/authelia/blob/master/examples/compose/lite/docker-compose.yml
  # https://www.youtube.com/watch?v=u6H-Qwf4nZA&t=949s&ab_channel=TechnoTim
  # authelia:
  #   image: authelia/authelia
  #   container_name: authelia
  #   volumes:
  #     - authelia:/config
  #   networks:
  #     - net
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.authelia.rule=Host(`authelia.taquy.dev`)'
  #     - 'traefik.http.routers.authelia.entrypoints=https'
  #     - 'traefik.http.routers.authelia.tls=true'
  #     - 'traefik.http.routers.authelia.tls.certresolver=letsencrypt'
  #     - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9095/api/verify?rd=https://authelia.taquy.dev'  # yamllint disable-line rule:line-length
  #     - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
  #     - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
  #   ports:
  #     - 9095:9091
  #   restart: unless-stopped
  #   healthcheck:
  #     disable: true
  #   environment:
  #     - TZ=Australia/Melbourne
  
  # infra-redis:
  #   image: redis:alpine
  #   container_name: infra-redis
  #   volumes:
  #     - infra-redis:/data
  #   networks:
  #     - net
  #   ports:
  #     - 6380:80
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Vietnam/Hanoi

  traefik:
    image: traefik:2.4
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-vol:/certs
    networks:
      - taquy-proxy
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      AWS_ACCESS_KEY_ID: AKIAVZH6TJTW2VKI5M2Q
      AWS_REGION: ap-southeast-1
      AWS_SECRET_ACCESS_KEY: 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
      AWS_HOSTED_ZONE_ID: Z02333301P1AFTPV8N8YA
    labels:
      - traefik.http.routers.whoami.rule=Host(`traefik.taquy.dev`)
      - traefik.http.routers.my-container.middlewares=taquy@docker"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --certificatesResolvers.taquy.acme.storage=/etc/traefik/acme.json
      - --certificatesresolvers.taquy.acme.dnschallenge=true
      - --certificatesresolvers.taquy.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --certificatesresolvers.taquy.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.taquy.acme.dnschallenge.provider=route53
      - --certificatesresolvers.taquy.acme.dnschallenge.delayBeforeCheck=0
      - --certificatesresolvers.taquy.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --providers.providersThrottleDuration=10s
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certResolver=leresolver
      - --entrypoints.websecure.http.tls.domains[0].main=taquy.dev
      - --entrypoints.websecure.http.tls.domains[0].sans=*.taquy.dev
      #- --entryPoints.redis.address=:6379/tcp

  # whoami:
  #   image: containous/whoami
  #   container_name: whoami
  #   restart: unless-stopped
  #   labels:
  #     - traefik.http.routers.whoami.rule=Host(`whoami.taquy.dev`)
