version: '3'

volumes:
  jenkins-home-vol:
    external: true
  jenkins-cache-vol:
    external: true
  jenkins-logs-vol:
    external: true
  octopus-repository-vol:
    external: true
  octopus-artifacts-vol:
    external: true
  octopus-taskLogs-vol:
    external: true
  octopus-cache-vol:
    external: true
  octopus-import-vol:
    external: true
  mssql-vol:
    external: true
  nginx-logs-vol:
    external: true
  nginx-web-vol:
    external: true
  certbot-logs-vol:
    external: true
  certbot-ssl-vol:
    external: true
  backup-logs-vol:
    external: true
  backup-archives-vol:
    external: true

services:
  # backup tools
  backup-cron:
    container_name: backup-cron
    image: 397818416365.dkr.ecr.ap-southeast-1.amazonaws.com/taquy-backup-cron:latest
    user: root
    privileged: true
    restart: unless-stopped
    volumes:
      - backup-logs-vol:/data/backup/logs
      - backup-archives-vol:/data/backup/archives
      - /root/.aws:/root/.aws/
    environment:
      # every day at 00:00
      SCHEDULE: '0 0 * * *'
      BUCKET: 'taquy-backup'
  
  # load balancing tools
  nginx:
    container_name: nginx
    image: 397818416365.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:latest
    user: root
    privileged: true
    restart: unless-stopped
    volumes:
      - certbot-ssl-vol:/etc/letsencrypt
      - nginx-logs-vol:/var/log/nginx
      - nginx-web-vol:/var/www/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    network_mode: host

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-ssl-vol:/etc/letsencrypt
      - certbot-logs-vol:/var/log/letsencrypt
      - nginx-web-vol:/var/www/html
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  # cicd tools
  jenkins:
    container_name: jenkins
    image: 397818416365.dkr.ecr.ap-southeast-1.amazonaws.com/jenkins:latest
    user: root
    privileged: true
    restart: always
    ports:
      - 9091:8080
    environment:
      JENKINS_USER: root
      JENKINS_PASS: root1234
      JAVA_OPTS: -Xmx8192m -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.aws:/var/jenkins_home/.aws:ro
      - jenkins-home-vol:/var/jenkins_home
      - jenkins-cache-vol:/var/cache/jenkins
      - jenkins-logs-vol:/var/log/jenkins

  mssql:
    container_name: mssql
    image: 397818416365.dkr.ecr.ap-southeast-1.amazonaws.com/mssql:latest
    user: root
    privileged: true
    restart: always
    environment:
      SA_PASSWORD: "aD@R98xaYEctkKCn"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "aD@R98xaYEctkKCn", "-Q", "select 1"]
      interval: 10s
      retries: 10
    volumes:
      - mssql-vol:/var/opt/mssql

  octopus:
    container_name: octopus
    image: octopusdeploy/octopusdeploy:latest
    user: root
    privileged: true
    restart: always
    ports:
      - 9090:8080
      - 11111:10943
    environment:
      ACCEPT_EULA: "Y"
      OCTOPUS_SERVER_NODE_NAME: taquy
      DB_CONNECTION_STRING: Server=mssql,1433;Database=OctopusDeploy;User=sa;Password=aD@R98xaYEctkKCn
      ADMIN_USERNAME: root
      ADMIN_PASSWORD: aD@R98xaYEctkKCn
      ADMIN_EMAIL: taquy.pb@gmail.com
      # openssl rand 16 | base64
      MASTER_KEY: DR1OIkFzQxynWzfEY5DhXg==
      ServerApiKey:
      DISABLE_DIND: "Y"
    depends_on:
      - mssql
    volumes:
      - octopus-repository-vol:/repository
      - octopus-artifacts-vol:/artifacts
      - octopus-taskLogs-vol:/taskLogs
      - octopus-cache-vol:/cache
      - octopus-import-vol:/import

  octopus-tentacle:
    depends_on:
      - octopus
    container_name: octopus-tentacle
    image: octopusdeploy/tentacle:latest
    user: root
    privileged: true
    restart: always
    ports:
      - 10931:10933
    environment:
      ServerUsername: root
      ServerPassword: aD@R98xaYEctkKCn
      TargetName: octopus-deploy
      ListeningPort: 10931
      TargetRole: admin
      TargetEnvironment: api.taquy.com
      ServerUrl: https://octopus.taquy.com
      PublicHostNameConfiguration: https://octopus-tentacle.taquy.com
      ACCEPT_EULA: "Y"
  
networks:
  default:
    external: true
    name: infra