version: '3'

networks:
  taquy-traefik:
    external: true
volumes:
  traefik-ssl-vol:
    external: true
  infra-redis-vol:
    external: true

services:
  # https://github.com/authelia/authelia/blob/master/examples/compose/lite/docker-compose.yml
  # https://www.youtube.com/watch?v=u6H-Qwf4nZA&t=949s&ab_channel=TechnoTim
  # authelia:
  #   image: authelia/authelia
  #   container_name: authelia
  #   volumes:
  #     - authelia:/config
  #   networks:
  #     - net
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.authelia.rule=Host(`authelia.taquy.dev`)'
  #     - 'traefik.http.routers.authelia.entrypoints=https'
  #     - 'traefik.http.routers.authelia.tls=true'
  #     - 'traefik.http.routers.authelia.tls.certresolver=letsencrypt'
  #     - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9095/api/verify?rd=https://authelia.taquy.dev'  # yamllint disable-line rule:line-length
  #     - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
  #     - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
  #   ports:
  #     - 9095:9091
  #   restart: unless-stopped
  #   healthcheck:
  #     disable: true
  #   environment:
  #     - TZ=Australia/Melbourne
  
  infra-redis:
    image: redis:alpine
    container_name: infra-redis
    restart: unless-stopped
    volumes:
      - infra-redis-vol:/data
    networks:
      - taquy-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`infra-redis.taquy.dev`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecured"
    environment:
      - TZ=Vietnam/Hanoi

  traefik:
    image: traefik:2.4
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-vol:/certs
    networks:
      - taquy-traefik
    environment:
      TZ: "Vietnam/Hanoi"
      AWS_ACCESS_KEY_ID: AKIAVZH6TJTW2VKI5M2Q
      AWS_REGION: ap-southeast-1
      AWS_SECRET_ACCESS_KEY: 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
      AWS_HOSTED_ZONE_ID: Z02333301P1AFTPV8N8YA
    ports:
      - 80:80
      - 8080:8080
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecured.address=:443"

  whoami:
    image: containous/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - taquy-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.taquy.dev`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecured"