[general]
state_file = /var/awslogs/state/agent-state

[/var/log/syslog]
file = "/var/log/cloud-init-output.log"
log_group_name = "taquy-instance"
log_stream_name = "{hostname}/cloud-init-output"
datetime_format = %b %d %H:%M:%S