jenkins:
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: true
      users:
        - id: "admin"
          password: "admin"
        - id: "dev"
          password: "dev"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 4
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git
# credentials:
#   system:
#     domainCredentials:
#       - domain :
#           name: "github.com"
#           description: "GitHub"
#         credentials:
#         - basicSSHUserPrivateKey:
#             scope: SYSTEM
#             id: taquy-git
#             username: taquy
#             passphrase: ""
#             description: "SSH key to access taquy git"
#             privateKeySource:
#               directEntry:
#                 privateKey: ${SSH_PRIVATE_KEY}
unclassified:
  location:
    url: https://jenkins.taquy.dev
  awsCredentialsProvider:
    cache: false
# jobs:
#   - file: /usr/local/jenkins-casc.groovy