jenkins:
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: true
      users:
        - id: "admin"
          password: "admin"
        - id: "dev"
          password: "dev"
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 4
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git
credentials:
  system:
    domainCredentials:
      - domain :
          name: "github.com"
          description: "GitHub"
        credentials:
        - basicSSHUserPrivateKey:
            scope: SYSTEM
            id: taquy-git
            username: taquy
            passphrase: ""
            description: "SSH key to access taquy git"
            privateKeySource:
              directEntry:
                privateKey: ${SSH_PRIVATE_KEY}
# jobs:
#   - file: /usr/local/jenkins-casc.groovy