apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: taquy
  labels:
    zone: hanoi-vietnam
spec:
  storageClassName: mongo
  volumeName: mongo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi