apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: taquy
  labels:
    app: mongo
    environment: production
    zone: hanoi-vietnam
spec:
  # storageClassName: mongo
  volumeName: mongo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      name: mongo
      app: mongo
      environment: production
      zone: hanoi-vietnam