apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: taquy
  labels:
    name: mongo-pv
    zone: hanoi-vietnam
spec:
  storageClassName: nfs-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: taquy
    name: mongo-pvc
