kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongo
  namespace: taquy
  labels:
    name: mongo
    zone: hanoi-vietnam
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true