apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo
  namespace: taquy
  labels:
    name: mongo
    app: mongo
    environment: production
    zone: hanoi-vietnam
spec:
  storageClassName: mongo
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: taquy
    name: mongo
  local:
    fsType: ext4
    path: /mnt/taquy/mongo  
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - taquy