version: '3'

volumes:
  mongo-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/mongo
  redis-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/redis
  es-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/es
  app-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/tmp

services:
  # fluentd:
  #   container_name: fluentd
  #   image: 397818416365.dkr.ecr.ap-southeast-1.amazonaws.com/fluentd:latest
  #   restart: always
  #   depends_on:
  #     - es
  #   links:
  #     - es
  #   ports:
  #     - 24224:24224
  #     - 24224:24224/udp
  #   network_mode: bridge

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    expose:
      - "9200"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=true
      - cluster.name=taquy
      - node.name=taquy
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-vol:/usr/share/elasticsearch/data
    network_mode: bridge

  # kibana:
  #   container_name: kibana
  #   image: kibana:7.10.1
  #   restart: always
  #   links:
  #     - es
  #   ports:
  #     - 5601:5601
  #   environment:
  #     SERVER_NAME: kibana.taquy.com
  #     ELASTICSEARCH_HOSTS: https://es.taquy.com

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-vol:/data
    network_mode: bridge

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
      - 27018:27018
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    volumes:
      - mongo-vol:/data/db
    network_mode: bridge

  application:
    container_name: taquy-api
    image: 397818416365.dkr.ecr.ap-southeast-1.amazonaws.com/taquy-api:latest
    ports:
     - 90:3000
    restart: always
    depends_on:
      - fluentd
    links:
      - fluentd
      - es
      - mongo
      - redis
    volumes:
      - app-vol:/data/tmp
    network_mode: bridge
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access