version: '3'

volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/mongo
  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/redis
  es-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/es

services:
  fluentd:
    container_name: fluentd
    image: 397818416365.dkr.ecr.ap-southeast-1.amazonaws.com/fluentd:latest
    restart: always
    links:
      - es
    ports:
      - 24224:24224
      - 24224:24224/udp
    network_mode: bridge

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    restart: always
    expose:
      - "9200"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    network_mode: bridge

  kibana:
    container_name: kibana
    image: kibana:7.10.1
    restart: always
    links:
      - es
    ports:
      - "5601:5601"

  redis:
    container_name: taquy-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    network_mode: bridge

  mongo:
    container_name: taquy-mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
      - 27018:27018
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    volumes:
      - mongo-data:/data/db
    network_mode: bridge

  application:
    container_name: taquy-api
    image: 397818416365.dkr.ecr.us-east-1.amazonaws.com/taquy-api:latest
    ports:
     - 90:3000
    restart: always
    links:
      - fluentd
      - es
      - mongo
      - redis
    network_mode: bridge
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access
    network_mode: bridge